# Workflow to compile and build SD FAT Library test application with ARM toolchain.

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # Build on Ubuntu latest version.
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install ARM toolchain and build the whole project.
      - name: Install ARM toolchain
        run: arm-none-eabi-gcc --version

      - name: Make
        run: make
